### PR TITLE
Tutorials

### PR DESCRIPTION
**Pull request by polygnomial**
# Summary

Add tutorials 1-2 for Dataplicity, and tutorial 1 for Raspberry Pi setup.

## Test Plan

Convince some humans to give it a try.

## Related Issues

None. Will do finish more tutorials when I have a chance.

### CODE REVIEW

**Comment by lgnashold** [comment]
LGTM on first glance, will give it a shot soon.

**Review by lgnashold — APPROVED** [review]

**Comment by lgnashold** [comment]
For the linter, I personally don't really care about showing expected command output in this case, so feel free to turn that off or ignore it. It's probably worth adding the language to the code snippets, i.e. \```shell or \```bash

**Comment by polygnomial** [comment]
Yeah the only abnormal thing is the 15mb of screenshots I included. I think it's fine though.

**Comment by polygnomial** [comment]
Sure I can do that. Tbh I haven't really been paying too much attention for doc commits.

**Comment by kevtan** [comment]
Could we use [git lfs](https://git-lfs.github.com/) to store these images? It would keep clone times small and gives us a good way to track changes to binaries like images.

**Comment by lgnashold** [comment]
I'll second using Git LFS to store images though.

**Review by lgnashold — CHANGES_REQUESTED** [review]
Lets get the images out of this PR before merging actually

**Pull request closed without merging**
