### PR TITLE
Create Tutorial 3

### PR DESCRIPTION
**Pull request by lgnashold**
# Summary

Add new Dataplicity / PyCubed tutorial 

## Test Plan

Tested by me, running all these commands on PyCubed

### CODE REVIEW

**Comment by polygnomial** [comment]
Overall, the content looks pretty good. Two general comments
1. we should move this out of the Dataplicity tutorials because it does not really focus on that at all. We are doing everything over Dataplicity at the moment but that will change in the future
2. There are a lot of small grammatical errors that should be fixed (i.e. tty -> TTY).

**Comment by lgnashold** [comment]
Should be better now

**Comment by polygnomial** [comment]
Looks good, there are some remaining `cu` and `screen` references that aren't monospaced (I think consistency here is important).

**Review by polygnomial — APPROVED** [review]
LGTM

**Pull request merged**
