### PR TITLE
Update submodule tracking commit with new firmware and bootloader

### PR DESCRIPTION
**Pull request by polygnomial**
# Summary

Update this repo to track the latest branch of the `stanford-ssi/pycubed-firmware` repo.

## Test Plan

Loaded the new bootloader on the PyCubed with SAMD51J20A and the CircuitPython firmware and it works fine.

### CODE REVIEW

**Comment by polygnomial** [comment]
Ready to merge!

**Comment by polygnomial** [comment]
I'll take that as your stamp of approval

**Comment by lgnashold** [comment]
lgtm

**Review by lgnashold — APPROVED** [review]

**Review by Timvrakas — COMMENTED** [review]
Not Rust, therefore not up to coding standards. 💥

**Comment by polygnomial** [comment]
okay boomer

**Pull request merged**
